#!/usr/bin/env python3 

import subprocess
import sys
from pathlib import Path

import exceptions
import utils
from constants_classes import SCCSConstants


def get_script_directory() -> Path:
    """Return the absolute path of the parent directory of this file."""
    return Path(__file__).parent.resolve()


def run_command(c: SCCSConstants, entered_command: str) -> None:
    """
    Run the entered command by running a subprocess of the command and exiting with the
    exit code of the subprocess.
    """
    sys.exit(
        subprocess.run(
            [
                sys.executable,
                Path(
                    get_script_directory() / entered_command
                ).with_suffix(c.PYTHON_EXTENSION),
            ]
            + sys.argv[c.COMMAND_ARGUMENT_INDEX:]
        ).returncode
    )


def validate_command(c: SCCSConstants, entered_command: str) -> None:
    """
    Validate the entered command by checking that it is included in the accepted
    commands. Raise an SCCSException if the command is unknown.
    """

    if entered_command not in c.COMMANDS_LIST:
        raise exceptions.SCCSException(
            c.UNKNOWN_COMMAND_ERROR_MESSAGE_TEMPLATE.format(
                entered_command=entered_command
            )
        )


def main(c: SCCSConstants, entered_command: str) -> None:
    """
    Run the entered command by validating it and running it as a subprocess, and exit
    with the exit code of the subprocess.
    """
    validate_command(c, entered_command)
    run_command(c, entered_command)


if __name__ == "__main__":
    c = SCCSConstants()
    utils.run_command(main, utils.entered_argument(c, c.COMMAND_ARGUMENT_INDEX))

# If on MacOS / Linux, move all files in commands/, and make this file executable
# with 'chmod +x /usr/local/bin/sccs'.
