#!/usr/bin/env python3 
"""SCCS - Simple Contract Control System; CLI tunnel to point to chosen command"""

from pathlib import Path
import subprocess
import sys

import exceptions
import utils
from constants_classes import SCCSConstants


def get_script_directory() -> Path:
    """Return the absolute path of the parent directory of this file."""
    return Path(__file__).parent.resolve()


def run_command(c: SCCSConstants, entered_command: str) -> None:
    """
    Run the entered command by running a subprocess of the command and exiting with the
    exit code of the subprocess.
    """
    sys.exit(
        subprocess.run(
            [
                sys.executable,
                Path(
                    get_script_directory() / entered_command
                ).with_suffix(c.PYTHON_EXTENSION),
            ]
            + sys.argv[1:]
        ).returncode
    )


def validate_command(c: SCCSConstants, entered_command: str) -> None:
    """
    Ensure 'command' is valid by checking if it is included in 'COMMANDS'. If command'
    is valid, run it with 'run_command()'.
    """

    if entered_command not in c.COMMANDS_LIST:
        raise exceptions.UnknownCommandError(
            c.UNKNOWN_COMMAND_ERROR_MESSAGE_TEMPLATE.format(
                entered_command=entered_command
            )
        )


def main(c: SCCSConstants, entered_command: str) -> None:
    validate_command(c, entered_command)
    run_command(c, entered_command)


if __name__ == "__main__":
    utils.run_command(main, utils.entered_argument(1))

# If on MacOS / Linux, move all files in commands/, and make this file executable
# with `chmod +x /usr/local/bin/sccs`.
