#!/usr/bin/env python3 
"""SCCS - Simple Contract Control System; CLI tunnel to point to chosen command"""

import subprocess
import sys
from pathlib import Path

import exceptions
import utils
from constants_classes import SCCSConstants, ErrorWrappers


def get_script_directory() -> Path:
    """Return the absolute path of the parent directory of this file."""
    return Path(__file__).parent.resolve()


def run_command(constants: SCCSConstants, entered_command: str) -> None:
    """
    Run the entered command by running a subprocess of the command and exiting with the
    exit code of the subprocess.
    """
    sys.exit(
        subprocess.run([
            sys.executable,
            get_script_directory() / entered_command + constants.PYTHON_EXTENSION,]
             + sys.argv[1:]
        ).returncode
    )


def validate_command(constants: SCCSConstants, entered_command: str) -> None:
    """
    Ensure 'command' is valid by checking if it is included in 'COMMANDS'. If command'
    is valid, run it with 'run_command()'.
    """

    if entered_command not in constants.COMMANDS_LIST:
        raise exceptions.UnknownCommandError(
            constants.UNKNOWN_COMMAND_ERROR_MESSAGE_TEMPLATE.format(entered_command=entered_command)
        )


def main(constants: SCCSConstants, entered_command: str) -> None:
    validate_command(constants, entered_command)
    run_command(constants, entered_command)


if __name__ == "__main__":
    try:
        constants = SCCSConstants()
        error_wrappers = ErrorWrappers()
        main(constants, utils.entered_argument(1))
    except exceptions.SCCSException as e:
        print(error_wrappers.EXPECTED_ERROR_TEMPLATE.format(e=e))
        sys.exit(1)

    except Exception as e:
        print(error_wrappers.UNEXPECTED_ERROR_TEMPLATE.format(type_name=type(e).__name__, e=e))
        sys.exit(2)

# If on MacOS / Linux, move this file, commit.py, init.py, open.py, log.py, diff.py,
# status.py, help.py, branch.py , and switch.py to /usr/local/bin and make it executable
#  with `chmod +x /usr/local/bin/sccs`.
