[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "sccs"
version = "0.1.0"
description = "Simple Contracts Communication System"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-docx",
    "mammoth",
    "requests",
    "beautifulsoup4",
]

[project.scripts]
sccs = "local_sccs.sccs:main"

[tool.setuptools.packages.find]
where = ["src"]